### ISSUE TITLE
Dell KB813t keyboard smart card reader asks for non existing pinpad 

### ISSUE THREAD

**Issue by annikajoymeitern** [open-eid/minidriver#47]
The problem persists after adding registry keys  [as suggested](https://github.com/open-eid/minidriver/wiki):

> [HKEY_LOCAL_MACHINE\SOFTWARE\RIA\minidriver]
> "disablepinpad"=dword:00000001
> [HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\RIA\minidriver]
> "disablepinpad"=dword:00000001

Smart card reader: Dell KB813t keyboard  smart card reader

Sysinfo:

> OS Name:                   Microsoft Windows 11 Home
> OS Version:                10.0.22621 N/A Build 22621
> OS Manufacturer:           Microsoft Corporation
> OS Configuration:          Standalone Workstation
> OS Build Type:             Multiprocessor Free
> Original Install Date:     10/19/2022, 9:46:19 AM
> System Boot Time:          11/7/2022, 9:07:05 PM
> System Manufacturer:       Gigabyte Technology Co., Ltd.
> System Model:              B660M DS3H DDR4
> System Type:               x64-based PC
> Processor(s):              1 Processor(s) Installed.
>                            [01]: Intel64 Family 6 Model 151 Stepping 5 GenuineIntel ~2500 Mhz
> BIOS Version:              American Megatrends International, LLC. F6, 8/8/2022
> Windows Directory:         C:\WINDOWS
> System Directory:          C:\WINDOWS\system32
> Boot Device:               \Device\HarddiskVolume1
> System Locale:             et;Estonian
> Input Locale:              et;Estonian
> Time Zone:                 (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
> Total Physical Memory:     16,158 MB
> Available Physical Memory: 10,747 MB
> Virtual Memory: Max Size:  18,590 MB
> Virtual Memory: Available: 13,110 MB
> Virtual Memory: In Use:    5,480 MB
> Page File Location(s):     C:\pagefile.sys
> Domain:                    WORKGROUP
> Hotfix(s):                 3 Hotfix(s) Installed.
>                            [01]: KB5017271
>                            [02]: KB5018496
>                            [03]: KB5019304
> Network Card(s):           1 NIC(s) Installed.
>                            [01]: Realtek Gaming 2.5GbE Family Controller
>                                  Connection Name: Ethernet
>                                  DHCP Enabled:    Yes

**Comment by metsma** [comment]
Is this Idemia or Gemlato card?

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
